### PR TITLE
Update formula and add automated InSpec integration tests.

### PR DESCRIPTION
**Pull request by johnbellone**
This commit updates the Chef formula to be a lot more simple. It also
uses newer, common idioms that I've seen in other formulas such as
defaults.yml usage. Finally, this adds test-kitchen support with
Travis, Docker and InSpec for integration testing.

### CODE REVIEW

**Comment by aboe76** [comment]
@johnbellone, It looks nice, good improvements but why remove the deprovision.sls?

**Comment by johnbellone** [comment]
@aboe76 Ah, I missed that, I'll fix it!

**Comment by johnbellone** [comment]
@aboe76 Would you also be able to enable Travis? This will run the kitchen integration tests on each pull request in a docker container.

**Comment by johnbellone** [comment]
You can see latest example here: https://travis-ci.org/johnbellone/chef-formula/builds/265959095

**Comment by aboe76** [comment]
@johnbellone I'm sorry can't enable travis,

**Comment by aboe76** [comment]
@basepi can you enable travis?

**Comment by basepi** [comment]
I flipped the switch on travis-ci.org. Not sure if I need to do anything else, I've never actually set up travis....

**Comment by aboe76** [comment]
@basepi thanks, @johnbellone merged

**Pull request merged**
